### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by ghost** [videntity/djmsample#8]
Following your step by step instruction, I encounter many errors. Did you actually run it by yourself?

**Comment by ghost** [comment]
And: what is the status of this project? Is it still maintained? It looks promising though.

**Comment by aviars** [comment]
Hi @artur-scholz I had an assistant update these instructions.  They may vary depending on what version of Django you are using.  What specific errors did you receive?  I can try to help with more context/

In addition, I know the install of this software can be tricky.  We have an AMI with everything already configured.  The ID for that AMI is ami-27164930.

Please see this article. http://www.videntity.com/2016/10/be-your-own-api-dj-and-win-a-turntable/

-Alan

**Comment by flowersw** [comment]
`django == 1.9.5` should be `django==1.9.5` in requirements.txt. Also this is the traceback I got back on step 4:
```
[wflowers@localhost djmsample]$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 8, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 13, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 12, in <module>
    from .loader import MigrationLoader
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 27, in Migration
    app = models.CharField(max_length=255)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1072, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/wflowers/.local/share/virtualenvs/djmsample-lVE5NIxJ/lib/python3.6/site-packages/django/conf/__init__.py", line 120, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```
Also, there is a file which is a symlink, which should be removed, I believe (see PR #6 ). There's probably more here. We should make an automated build of this. Shouldn't be too hard with something like Travis.
